### ISSUE TITLE
votl_maketags.pl

### ISSUE THREAD

**Issue by GrahameBlackwood** [vimoutliner/vimoutliner#110] opened 2015-02-14 16:14 UTC
While testing Vimoutliner installed via Pathogen I've found two problems related to votl_maketags.pl

The first is that when I tried to use votl_maketags.pl to test interoutline linking like so:

~/.vim/bundle/vimoutliner/vimoutliner/scripts/votl_maketags.pl ~/votl_test.otl

This failed with an error message that I didn't have the necessary permissions. I noticed that votl_maketags.pl is not executable, but it used to be in the  previous version of Vimoutliner. Perhaps votl_maketags.pl should be made executable. 

The second occurred after I made votl_maketags.pl executable and tried to run it again. the following errors were produced :

: sort: cannot read: /home/g2/.vim/vimoutliner/vo_tags.tag: No such file or directory
: rm: cannot remove: /home/g2/.vim/vimoutliner/vo_tags.tag: No such file or directory
: mv: cannot move: /home/g2/temptagfile.tag to /home/g2/.vim/vimoutliner/vo_tags.tag: No such file or directory

Also this left an empty file temptagfile.tag at /home/g2/ 

Perhaps this is an aberration in the set up on my pc but I notice votl_maketags.pl has the following line and wondered if it might have something to do with the error messages:
$TAGFILENAME = $ENV{"HOME"} . "/.vim/vimoutliner/vo_tags.tag";

Grahame

**Comment by mcepl** [comment] 2015-02-16 10:16
We can fix the exec bit of the script, but there are many things not right. @jostber , you have added the script to the git, do you have any idea about Perl programming? And I believe Steve is the original author, but I don't think he is around Github (is he?).

Just by five-minutes browsing I see this:
* [ ] https://github.com/vimoutliner/vimoutliner/blob/master/vimoutliner/scripts/votl_maketags.pl#L112 ... really, temporary files in `$HOME`? Ever heard about `mkstemp()` or its Perl equivalents?
* [ ] https://github.com/vimoutliner/vimoutliner/blob/master/vimoutliner/scripts/votl_maketags.pl#L159 and others ... doing `open()` for writing and not checking whether the directory exist is probably the root cause of your problems, @GrahameBlackwood , because without Pathogen this script could always bet that `~/.vim/vimoutliner` exists, but it is very unsafe and unwise thing not to check for existence of the directory.
* [ ] all the functions like `fileExists`, `getBaseDirectory`, or `makeDirectory` make me shiver. Really, perl doesn't have functions for this in the standard library?

**Comment by zmughal** [comment] 2015-02-16 12:42
Oooh. This Perl is just not very good. Not even by old standards. I will look into rewriting it, if that's OK?

Here's an [example](https://github.com/zmughal/p5-Devel-IPerl/blob/master/bin/iperl) of a Perl script I wrote just the other day.

**Comment by jostber** [comment] 2015-02-16 16:03
On 16.02.15,04:42, Zaki Mughal [sivoais] wrote:
> Oooh. This Perl is just not very good. Not even by old standards. I will look into rewriting it, if that's OK?
> 
> Here's an [example](https://github.com/zmughal/p5-Devel-IPerl/blob/master/bin/iperl) of a Perl script I wrote just the other day.
> 

That is OK with me, this is a quite old script that needs some cleaning u. 

u

**Comment by mcepl** [comment] 2015-02-16 17:32
Couldn't we actually port it to Python (or Ruby if you really insist)? I would really like to decrease number of languages used inside of VimOutliner and Perl seems to be easiest one to exorcise.

**Comment by jostber** [comment] 2015-02-16 18:03
On 16.02.15,09:32, Matěj Cepl wrote:
> Couldn't we actually port it to Python (or Ruby if you really insist)? I would really like to decrease number of languages used inside of VimOutliner and Perl seems to be easiest one to exorcise.
> 

I agree that it would be better to keep the scripts to one or two
languages, and both ruby and python works fine in this context. iIs this
script also very useful anymore when the UTL vim plugin covers all the
scripts does and a lot more as well?

http://www.vim.org/scripts/script.php?script_id=293


Jostein

**Comment by mcepl** [comment] 2015-02-17 12:09
OK, so perhaps @jostber is right. 

@GrahameBlackwood is UTL what you actually want? If not, would anybody finish my pull request (this is just untested draft)?

**Comment by GrahameBlackwood** [comment] 2015-02-17 16:36
Hi Matěj

On Tue, Feb 17, 2015 at 12:10 PM, Matěj Cepl <notifications@github.com> wrote:

> from: "Matěj Cepl" <notifications@github.com>
> date: Tue, Feb 17 04:10 AM -08:00 2015
> to: vimoutliner/vimoutliner <vimoutliner@noreply.github.com>
> cc: GrahameBlackwood <grahameblackwood@gmail.com>
> reply-to: vimoutliner/vimoutliner <reply@reply.github.com>
> subject: Re: [vimoutliner] votl_maketags.pl (#110)
> 
> OK, so perhaps @jostber is right. 
> 
> @GrahameBlackwood is UTL what you actually want? If not, would anybody finish my pull request (this is just untested draft)?
> 

I haven't heard about UTL until this conversation developed, so I can't say it
it's what I want. I'll install it and try it out.

Cheers

G

**Comment by zmughal** [comment] 2015-02-17 19:34
@mcepl heh, yeah, it's evil, but it gets the job done! :-P

Also, doing a direct translation won't fix the bugs in that code.

**Comment by mcepl** [comment] 2015-02-19 21:59
> Also, doing a direct translation won't fix the bugs in that code.

??? I believe I have avoided all bugs I have mentioned.

**Comment by zmughal** [comment] 2015-02-23 03:13
Yes, those aren't the bugs I see, but there are still some design issues in the original script that should not be ported over. That's why I rewrote the entire structure in #112 to separate the concerns of each function.

I made some comments on #111.

**Comment by mcepl** [comment] 2015-02-24 18:59
@zmughal Could you please review #111 again? I have made complete rewrite based on your Perl script in #112. You are right, that zombie is not worthy to be revived.

What do you think?

**Comment by zmughal** [comment] 2015-02-24 19:30
Done! It looks much better.

**Closed** 2015-09-27 16:48 UTC
Labels: Bug
